config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "marketplace#index"
  resources :programs
  resources :users, only: [:show]
  namespace :programs do
    resources :weeks, only: [:create, :show]
    resources :days, only: [:create, :show]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :week
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :user
  has_many :weeks, dependent: :destroy

  MAX_WEEKS = 4
  MAX_DAYS = 14

  validates :title, presence: true
  validates :num_weeks, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: MAX_WEEKS }
  # incase they are doing 7 2/days
  validates :days_per_week, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: MAX_DAYS }
end

app/models/training.rb
class Training < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/volume.rb
class Volume < ApplicationRecord
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :program
  has_many :days, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marketplace_controller.rb
class MarketplaceController < ApplicationController
end

app/controllers/program/days_controller.rb
class Program::DaysController < ApplicationController
end

app/controllers/program/training_controller.rb
class Program::TrainingController < ApplicationController
end

app/controllers/program/weeks_controller.rb
class Program::WeeksController < ApplicationController
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :program, only: %i[show edit update destroy]

  def index
    @programs = Program.all
  end

  def new
    @program = Program.new
  end

  def edit; end

  def show; end

  def create
    @program = Program.new(program_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @program.save
        ProgramService.call(@program.id, @program.num_weeks, @program.days_per_week)
        format.html { redirect_to root_path, notice: I18n.t('admin.loafs.success.updated') }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: I18n.t('admin.loafs.success.updated') }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @program.update(loaf_params)
        format.html { redirect_to root_path, notice: I18n.t('admin.loafs.success.updated') }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def program
    @program ||= Program.find(params[:id])
  end

  def program_params
    params.require(:program).permit(:title, :num_weeks, :days_per_week, :cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/program/day_helper.rb
module Program::DayHelper
end

app/helpers/program/training_helper.rb
module Program::TrainingHelper
end

app/helpers/program/week_helper.rb
module Program::WeekHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
<div>
  <div class=" sm:block">
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex" aria-label="Tabs">
        <!-- Current: "border-indigo-500 text-indigo-600", Default: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300" -->
        <%= link_to 'Programs', programs_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
        <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
      </nav>
    </div>
  </div>
</div>
<% else %>
<%= link_to 'Sign In', new_user_session_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/marketplace/index.html.erb
<h1>home</h1>

app/views/programs/days/index.html.erb
<h1> Days </h1>

app/views/programs/index.html.erb
<div class="w-full h-auto overflow-y-scroll"> 
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Program Marketplaace</h1>
      <p class="mt-2 text-sm text-gray-700">Get Fit, Stay Fit, Help Others</p>
    </div>
  </div>
  <div class="w-full pt-20">
    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
    <% @programs.each do |program| %>
      <li class="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200 ">
        <div class=" flex items-center justify-between p-6 space-x-6">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">
              <h3 class="text-gray-900 text-sm font-medium truncate"> <%= program.title %></td></h3>
              <%= link_to "show", program_path(program.id) %>

            </div>
            <p class="mt-1 text-gray-500 text-sm truncate">Cost: $<%= program.cost %></td>  </p>
            <p class="mt-1 text-gray-500 text-sm truncate">Weeks: <%= program.num_weeks %></td>  </p>
            <p class="mt-1 text-gray-500 text-sm truncate">Days: <%= program.days_per_week %></td>  </p>
          </div>
        </div>
      </li>
    <% end %>

    </ul>
  </div>
</div>

app/views/programs/new.html.erb
<div class="mx-auto md:w-2/3 w-full overflow-y-scroll">
  <h1 class="font-bold text-4xl">New Program</h1>
  <%= form_for @program, url: {action: "create"} do |form| %>
    <% if @program.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

        <ul>
          <% @program.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :cost %>
      <%= form.text_field :cost, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :days_per_week %>
      <%= form.text_field :days_per_week, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :num_weeks %>
      <%= form.text_field :num_weeks, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/programs/show.html.erb
<%= @program.inspect %>
<br>
<% @program.weeks.each do |week| %>
    <%= week.title %>
    <br>
    <% week.days.each do |day| %>
        <%= day.title %>
        <br>
    <% end %>
<% end %>